test:
	javac -cp "gleipner.chains-1.0-jni.jar" DeserializationTest.java
	java -cp "gleipner.chains-1.0-jni.jar:." DeserializationTest serialize file.ser
	java -cp "gleipner.chains-1.0-jni.jar:." DeserializationTest file.ser
