/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gleipner_chains_jni_Custom001Trampoline */

#ifndef _Included_gleipner_chains_jni_Custom001Trampoline
#define _Included_gleipner_chains_jni_Custom001Trampoline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gleipner_chains_jni_Custom001Trampoline
 * Method:    native0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gleipner_chains_jni_Custom001Trampoline_native0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
