depth:
	 python3 algorithms.py --store --run -p serhybrid --jar _target/gleipner.chains-1.0-depth.jar
	 python3 algorithms.py --store --run -p jchainz --jar _target/gleipner.chains-1.0-depth.jar
	 python3 algorithms.py --store --run -p tabby --jar _target/gleipner.chains-1.0-depth.jar
	 python3 algorithms.py --store --run -p gadgetinspector --jar _target/gleipner.chains-1.0-depth.jar
	 python3 algorithms.py --store --run -p serianalyzer --jar _target/gleipner.chains-1.0-depth.jar


depth-result:
	java -jar evaluator.jar _output/serianalyzer_depth.txt _target/gleipner.chains-1.0-depth.jar serianalyzer
	java -jar evaluator.jar _output/gadgetinspector_depth.txt _target/gleipner.chains-1.0-depth.jar gadgetinspector
	java -jar evaluator.jar _output/serhybridpub_depth.txt _target/gleipner.chains-1.0-depth.jar serhybrid
	java -jar evaluator.jar _output/JChainz_depth.txt _target/gleipner.chains-1.0-depth.jar jchainz
	java -jar evaluator.jar _output/tabby_depth.txt _target/gleipner.chains-1.0-depth.jar tabby


polymorphism:
	 python3 algorithms.py --store --run -p serhybrid --jar _target/gleipner.chains-1.0-polymorphism.jar
	 python3 algorithms.py --store --run -p jchainz --jar _target/gleipner.chains-1.0-polymorphism.jar
	 python3 algorithms.py --store --run -p tabby --jar _target/gleipner.chains-1.0-polymorphism.jar
	 python3 algorithms.py --store --run -p gadgetinspector --jar _target/gleipner.chains-1.0-polymorphism.jar
	 python3 algorithms.py --store --run -p serianalyzer --jar _target/gleipner.chains-1.0-polymorphism.jar


polymorphism-result:
	java -jar evaluator.jar _output/serianalyzer_polymorphism.txt _target/gleipner.chains-1.0-polymorphism.jar serianalyzer
	java -jar evaluator.jar _output/gadgetinspector_polymorphism.txt _target/gleipner.chains-1.0-polymorphism.jar gadgetinspector
	java -jar evaluator.jar _output/serhybridpub_polymorphism.txt _target/gleipner.chains-1.0-polymorphism.jar serhybrid
	java -jar evaluator.jar _output/JChainz_polymorphism.txt _target/gleipner.chains-1.0-polymorphism.jar jchainz
	java -jar evaluator.jar _output/tabby_polymorphism.txt _target/gleipner.chains-1.0-polymorphism.jar tabby


multipath:
	 python3 algorithms.py --store --run -p serhybrid --jar _target/gleipner.chains-1.0-multipath.jar
	 python3 algorithms.py --store --run -p jchainz --jar _target/gleipner.chains-1.0-multipath.jar
	 python3 algorithms.py --store --run -p tabby --jar _target/gleipner.chains-1.0-multipath.jar
	 python3 algorithms.py --store --run -p gadgetinspector --jar _target/gleipner.chains-1.0-multipath.jar
	 python3 algorithms.py --store --run -p serianalyzer --jar _target/gleipner.chains-1.0-multipath.jar


multipath-result:
	java -jar evaluator.jar _output/serianalyzer_multipath.txt _target/gleipner.chains-1.0-multipath.jar serianalyzer
	java -jar evaluator.jar _output/gadgetinspector_multipath.txt _target/gleipner.chains-1.0-multipath.jar gadgetinspector
	java -jar evaluator.jar _output/serhybridpub_multipath.txt _target/gleipner.chains-1.0-multipath.jar serhybrid
	java -jar evaluator.jar _output/JChainz_multipath.txt _target/gleipner.chains-1.0-multipath.jar jchainz
	java -jar evaluator.jar _output/tabby_multipath.txt _target/gleipner.chains-1.0-multipath.jar tabby


